# based on https://github.com/pcolby/aws-sdk-qt/blob/master/.travis.yml
language: cpp
compiler:
  - clang
  - gcc

os:
  - linux
  - osx

dist: trusty

env:
  - CONFIG=RELEASE QT=59 BREW=ex PPA=beineri/opt-qt593-trusty

before_install:
  - '[[ "$TRAVIS_OS_NAME" != linux || -z "$PPA" ]] || sudo add-apt-repository -y ppa:$PPA'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx   ] || brew update'

  # Qt5
  - sudo apt-add-repository --yes ppa:$PPA
  - sudo apt-get -qq update

install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install doxygen graphviz lcov'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || sudo apt-get -qy install qt${QT}base qt${QT}xmlpatterns'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev'
  - '[ "$TRAVIS_OS_NAME" != linux ] || gem install lcoveralls'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install doxygen graphviz qt$BREW'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$BREW'
  - qmake -v


before_script:
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
  - mkdir -p "$TRAVIS_BUILD_DIR-build"
  - qmake -o "$TRAVIS_BUILD_DIR-build" -r -Wall -Wlogic -Wparser CONFIG+="$CONFIG" "$TRAVIS_BUILD_DIR"

script:
  - make -C "$TRAVIS_BUILD_DIR-build" all
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 check TESTARGS=-silent
  - ls "$TRAVIS_BUILD_DIR-build"


before_deploy: "cd $TRAVIS_BUILD_DIR-build && tar -zcvf ../ImageMosaicWall-$TRAVIS_TAG.tar.gz . && cd .."
deploy:
  provider: releases
  api_key:
    secure: faqXDjv3SX3BYg36+a4xvFZ5L26sIz1u7edjtj1KgqIqUPrBXfj1FAkEjpEAlvLlS0OL2OaJghXua1NuZlzL7+dl2eRtD32oZWyejUS+jy2yFwRJ3oSXGL5T20MM5xFUpDXRm6VuoIFVfuzieJqzz7gVPMr/uT1JnCqbB3GEtAc=
  file: "ImageMosaicWall-$TRAVIS_TAG.tar.gz"
  skip_cleanup: true
  on:
    repo: scheckmedia/ImageMosaicWall
    tags: true
